/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProjectId = IDL.Text;
export const Filter = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Threshold = IDL.Nat8;
export const ChromaKey = IDL.Record({
  'red' : Threshold,
  'threshold' : Threshold,
  'blue' : Threshold,
  'green' : Threshold,
});
export const Project = IDL.Record({
  'id' : ProjectId,
  'filters' : IDL.Vec(Filter),
  'background' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'chromaKey' : ChromaKey,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addFilter' : IDL.Func([ProjectId, Filter], [], []),
  'createProject' : IDL.Func([ProjectId, IDL.Text], [], []),
  'deleteProject' : IDL.Func([ProjectId], [], []),
  'getProject' : IDL.Func([ProjectId], [Project], ['query']),
  'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'setBackground' : IDL.Func([ProjectId, IDL.Opt(ExternalBlob)], [], []),
  'updateChromaKey' : IDL.Func([ProjectId, ChromaKey], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProjectId = IDL.Text;
  const Filter = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Threshold = IDL.Nat8;
  const ChromaKey = IDL.Record({
    'red' : Threshold,
    'threshold' : Threshold,
    'blue' : Threshold,
    'green' : Threshold,
  });
  const Project = IDL.Record({
    'id' : ProjectId,
    'filters' : IDL.Vec(Filter),
    'background' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'chromaKey' : ChromaKey,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addFilter' : IDL.Func([ProjectId, Filter], [], []),
    'createProject' : IDL.Func([ProjectId, IDL.Text], [], []),
    'deleteProject' : IDL.Func([ProjectId], [], []),
    'getProject' : IDL.Func([ProjectId], [Project], ['query']),
    'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'setBackground' : IDL.Func([ProjectId, IDL.Opt(ExternalBlob)], [], []),
    'updateChromaKey' : IDL.Func([ProjectId, ChromaKey], [], []),
  });
};

export const init = ({ IDL }) => { return []; };